version: "3.7"

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always
  item-app:
    image: carbonite12/item-app:v1
    ports:
      - 8080:8080
    depends_on:
      - item-db
    restart: always
    
volumes:
  app-db: